DROP VIEW IF EXISTS `$$VIEW_NAME$$`;

CREATE VIEW `$$VIEW_NAME$$` AS
SELECT
    project_id,
    project_name,
    project_description,
    date,
    search_engine,
    region_id,
    region_name,
    is_mobile,
    group_count,
    queries_groups_count,
    queries_count,
    documents_count,
    categories_count,
    frequency1,
    frequency2,
    frequency3,
    top3_count,
    top5_count,
    top10_count,
    top100_count,
    top3_percent,
    top5_percent,
    top10_percent,
    top100_percent,
    frequency1_top10_percent,
    frequency2_top10_percent,
    frequency1_top10_count,
    frequency2_top10_count,
    potential_traffic as potential_traffic_count,
    potential_traffic_percent,
    worth,
    worth_max,
    worth_reserve,
    worth_percent
FROM `$$TABLE_NAME$$`;
